### ISSUE TITLE
Handle correctly domainless accounts

### ISSUE THREAD

**Issue by jsanz** [jsanz/carto_cli#2]
On-Premises installations use domainless url schema, review the way the URLs are used to be sure commands work in these cases.

**Comment by arredond** [comment]
Building up on this:

On-Prem setup is quite unintuitive right now. Apparently, the URL must be of the type `http(s)://{onprem_url}/user/{user}`, whereas one would expect to only have to input the domain name (`http(s)://{onprem_url}`). This example in the README builds up that confusion, since it doesn't include the `/user/{user}` bit:

```yaml
another_user:
  api_key: your_api_key
  organization: myorg
  url: http://myserver.mydomain.com
```

Maybe this example could be updated to better reflect a proper On-Premise url? Such as:

```yaml
# Add the user to the URL for On-premise accounts
on_premise_user:
  api_key: your_api_key
  organization: myorg
  url: http://myserver.mydomain.com/user/on_premise_user
```

Of course, actually detecting an On-prem and properly parsing the URL would be even better, but just this small change, and also maybe adding a small line such as:

> On-Premise installations should use the following structure for their URLs: `http(s)://{onprem_url}/user/{user}`

would already greatly clarify this topic.

As always, thanks for your awesome work! I've been using this a lot for the past week and it's really  improved my workflow already.
